/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nayan/Sourav
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class Examination extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Examination() {
        initComponents();
         Show_Marks_In_JTable();
           Toolkit toolkit = getToolkit();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
     public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/test", "root","");
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
       public ArrayList<Marks> getMarksList()
   {
       ArrayList<Marks> marksList = new ArrayList<Marks>();
       Connection connection = getConnection();
       
       String query = "SELECT * FROM  `marks` ";
       Statement st;
       ResultSet rs;
       
       try {
           st = connection.createStatement();
           rs = st.executeQuery(query);
           Marks mark;
           while(rs.next())
           {
               mark = new Marks(rs.getString("id"),rs.getInt("pc"),rs.getInt("maths"),rs.getInt("english"),rs.getInt("cfo"),rs.getInt("os"),rs.getInt("total"),rs.getDouble("percentage"),rs.getDouble("cgpa"));
               marksList.add(mark);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
       return marksList;
   }
    public void Show_Marks_In_JTable()
   {
       ArrayList<Marks> list = getMarksList();
       DefaultTableModel model = (DefaultTableModel)jTable_Display_Marks.getModel();
       Object[] row = new Object[9];
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getId();
           row[1] = list.get(i).getPc();
           row[2] = list.get(i).getMaths();
           row[3] = list.get(i).getEnglish();
           row[4]=list.get(i).getCfo();
           row[5] = list.get(i).getOs();
           row[6] = list.get(i).getTotal();
           row[7] = list.get(i).getPercentage();
           row[8] = list.get(i).getCgpa();
           
           model.addRow(row);
       }
    }
    public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
               
           {
              
               DefaultTableModel model = (DefaultTableModel)jTable_Display_Marks.getModel();
               model.setRowCount(0);
               Show_Marks_In_JTable();
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_Marks = new javax.swing.JTable();
        jmaths = new javax.swing.JTextField();
        jenglish = new javax.swing.JTextField();
        jos = new javax.swing.JTextField();
        jpc = new javax.swing.JTextField();
        jid = new javax.swing.JTextField();
        jcfo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Display_Marks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        jTable_Display_Marks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PC", "Maths", "Eng", "CFO", "OS", "Total", "%", "CGPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Display_Marks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_MarksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Display_Marks);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 30, 430, 400));
        getContentPane().add(jmaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 120, 30));
        getContentPane().add(jenglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 120, 30));
        getContentPane().add(jos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 30));

        jpc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpcKeyReleased(evt);
            }
        });
        getContentPane().add(jpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 120, 30));

        jid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jidKeyReleased(evt);
            }
        });
        getContentPane().add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 120, 30));
        getContentPane().add(jcfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 120, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("OS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 70, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 70, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("PC");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Maths");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("English");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 70, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("CFO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 70, 30));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-restart-48.png"))); // NOI18N
        update.setContentAreaFilled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 50, 50));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-48.png"))); // NOI18N
        delete.setContentAreaFilled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 50, 50));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-48.png"))); // NOI18N
        add.setContentAreaFilled(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 60, -1));

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-go-back-48.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Examination.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
      AdminPanel obj = new AdminPanel();
      obj.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       int pct=Integer.valueOf(jpc.getText());
       int mathst=Integer.valueOf(jmaths.getText());
       int englisht=Integer.valueOf(jenglish.getText());
       int cfot=Integer.valueOf(jcfo.getText());
       int ost=Integer.valueOf(jos.getText());
       int total=pct+mathst+englisht+cfot+ost;
       float percentage=total/5;
       float cgpa=(float) (percentage/9.5);
      
         String query = "INSERT INTO `marks` (`id`, `pc`, `maths`,`english`,`cfo`,`os`,`total`,`percentage`,`cgpa`) VALUES ('"+jid.getText()+"',"+pct+","+mathst+","+englisht+","+cfot+","+ost+","+total+","+percentage+","+cgpa+")";
         executeSQlQuery(query, "Inserted");
 
         
        
    }//GEN-LAST:event_addActionPerformed

    private void jTable_Display_MarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_MarksMouseClicked
        // TODO add your handling code here:
          int i = jTable_Display_Marks.getSelectedRow();

        TableModel model = jTable_Display_Marks.getModel();
        
         // Display Slected Row In JTextFields
        jid.setText(model.getValueAt(i,0).toString());

        jpc.setText(model.getValueAt(i,1).toString());

        jmaths.setText(model.getValueAt(i,2).toString());
        
        jenglish.setText(model.getValueAt(i,3).toString());
        jcfo.setText(model.getValueAt(i,4).toString());

        jos.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_jTable_Display_MarksMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      int pct=Integer.valueOf(jpc.getText());
       int mathst=Integer.valueOf(jmaths.getText());
       int englisht=Integer.valueOf(jenglish.getText());
       int cfot=Integer.valueOf(jcfo.getText());
       int ost=Integer.valueOf(jos.getText());
       int total=pct+mathst+englisht+cfot+ost;
       float percentage=total/5;
       float cgpa=(float) (percentage/9.5);
        String query = "UPDATE `marks` SET `id`='"+jid.getText()+"',`pc`="+pct+",`maths`="+mathst+",`english`="+englisht+",`cfo`="+cfot+",`os`="+ost+",`total`="+total+",`percentage`="+percentage+",`cgpa`="+cgpa+" WHERE `id` = '"+jid.getText()+"'";
       executeSQlQuery(query, "Updated");
       
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
   //String query = "DELETE FROM `users` WHERE id = "+jid.getText();
   String query = "DELETE FROM `marks` WHERE id = '"+jid.getText()+"'";
         executeSQlQuery(query, "Deleted");
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void jpcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpcKeyReleased

    }//GEN-LAST:event_jpcKeyReleased

    private void jidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jidKeyReleased
                int pos = jid.getCaretPosition();
        jid.setText(jid.getText().toUpperCase());
        jid.setCaretPosition(pos);
    }//GEN-LAST:event_jidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Display_Marks;
    private javax.swing.JTextField jcfo;
    private javax.swing.JTextField jenglish;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jmaths;
    private javax.swing.JTextField jos;
    private javax.swing.JTextField jpc;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
