
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nayan
 */
public class ResultAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Admin_result
     */
    public ResultAdmin() {
        initComponents();
          Toolkit toolkit = getToolkit();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        j_id = new javax.swing.JLabel();
        j_pc = new javax.swing.JLabel();
        J_maths = new javax.swing.JLabel();
        j_eng = new javax.swing.JLabel();
        j_cfo = new javax.swing.JLabel();
        j_os = new javax.swing.JLabel();
        Jtotal = new javax.swing.JLabel();
        j_percentage = new javax.swing.JLabel();
        j_cgpa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter ID to check");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 200, 40));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, 40));

        j_id.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        j_id.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(j_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, 30));

        j_pc.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        j_pc.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(j_pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 90, 30));

        J_maths.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        J_maths.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(J_maths, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 80, 30));

        j_eng.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        j_eng.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(j_eng, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 80, 30));

        j_cfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        j_cfo.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(j_cfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 90, 30));

        j_os.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        j_os.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(j_os, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 80, 30));

        Jtotal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Jtotal.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(Jtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 90, 30));

        j_percentage.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        j_percentage.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(j_percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 90, 30));

        j_cgpa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        j_cgpa.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(j_cgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 90, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-google-web-search-filled-50.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 40, 40));

        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-go-back-48.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marksss.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         this.setVisible(false);
        AdminPanel obj = new AdminPanel();
       obj.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String nid=id.getText();
       Database ob= new Database();
       String query= "SELECT * FROM `marks` WHERE `id`='"+nid+"'";
       ResultSet rs= ob.resultWithReturn(query);
        try {
            
                 
            if(rs.next())
            {
     String  pc=String.valueOf(rs.getInt("pc"));
        String maths=   String.valueOf(rs.getInt("maths"));
        String english=   String.valueOf(rs.getInt("english"));
        String cfo=   String.valueOf(rs.getInt("cfo"));
        String os=   String.valueOf(rs.getInt("os"));
        String total=   String.valueOf(rs.getInt("total"));
         String percentage=   String.valueOf(rs.getFloat("percentage"));
          String cgpa=   String.valueOf(rs.getFloat("cgpa"));
            
        j_id.setText(rs.getString("id"));
            j_pc.setText(pc);
            J_maths.setText(maths);
             j_eng.setText(english);
              j_cfo.setText(cfo);
               j_os.setText(os);
                Jtotal.setText(total);
                 j_percentage.setText(percentage);
                 j_cgpa.setText(cgpa);
          
            
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Not Found!!!");
            }  
        } catch (SQLException ex) {
            Logger.getLogger(ResultAdmin.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
       int position= id.getCaretPosition();
       id.setText(id.getText().toUpperCase());
       id.setCaretPosition(position);
        
    }//GEN-LAST:event_idKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_result.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_result.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_result.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_result.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J_maths;
    private javax.swing.JLabel Jtotal;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel j_cfo;
    private javax.swing.JLabel j_cgpa;
    private javax.swing.JLabel j_eng;
    private javax.swing.JLabel j_id;
    private javax.swing.JLabel j_os;
    private javax.swing.JLabel j_pc;
    private javax.swing.JLabel j_percentage;
    // End of variables declaration//GEN-END:variables
}
